defmodule MyApp.Repo.Migrations.AddPlugins do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:plugins, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text)
      add(:settings, :map)
    end
  end

  def down do
    drop(table(:plugins))
  end
end
